language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
script:
  - RAILS_ENV=test bin/rails db:migrate --trace
  - bin/rails db:test:prepare
  - bin/rails test
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database ccs_test;' -U postgres  