sudo: required
rvm:
  - 2.4.1
services:
  - docker
script:
  - docker exec backend bash -c 'RAILS_ENV=test bin/rails db:create'
  - docker exec backend bash -c 'RAILS_ENV=test bin/rails db:migrate --trace'
  - docker exec backend bash -c 'bin/rails db:test:prepare'
  - docker exec backend bash -c 'bin/rails test'
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push checkraiser/giftpoint-backend
before_script:
  - cp config/database.yml.travis config/database.yml
  - docker pull postgres:9.6
  - docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres
  - docker build -t checkraiser/giftpoint-backend . 
  - docker run --name backend --link some-postgres:postgres -e RAILS_ENV=test -d checkraiser/giftpoint-backend